alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias ll='ls -la --color=auto'
alias ..='cd ..'
alias bc='bc -l'
alias vi='vim'
alias edit='vim'
alias df='df -H'
alias du='du -ch'
alias rm='rm -i'
export PS1='\u-:\W$'

