adb shell pm disable-user --user 0 com.miui.cleanmaster
adb shell pm disable-user --user 0 com.miui.notes
adb shell pm disable-user --user 0 com.miui.android.fashiongallery
adb shell pm disable-user --user 0 com.mfashiongallery.emag
adb shell pm disable-user --user 0 com.miui.gallery
adb shell pm disable-user --user 0 com.android.wallpaper.livepicker
adb shell pm disable-user --user 0 com.mi.android.personalassistant
adb shell pm disable-user --user 0 com.miui.personalassistant
adb shell pm disable-user --user 0 com.android.dreams.basic
adb shell pm disable-user --user 0 com.android.stk
adb shell pm disable-user --user 0 com.miui.player
adb shell pm disable-user --user 0 com.xiaomi.discover
adb shell pm disable-user --user 0 com.xiaomi.mirecycle
adb shell pm disable-user --user 0 com.android.cellbroadcastreceiver
adb shell pm disable-user --user 0 com.google.android.feedback
adb shell pm disable-user --user 0 com.miui.klo.bugreport
adb shell pm disable-user --user 0 com.miui.weather2
adb shell pm disable-user --user 0 com.xiaomi.mipicks
adb shell pm disable-user --user 0 com.miui.hybrid
adb shell pm disable-user --user 0 com.miui.hybrid.accessory
adb shell pm disable-user --user 0 com.android.htmlviewer
adb shell pm disable-user --user 0 com.miui.backup
adb shell pm disable-user --user 0 com.miui.cloudservice
adb shell pm disable-user --user 0 com.miui.cloudbackup
adb shell pm disable-user --user 0 com.miui.micloudsync
adb shell pm disable-user --user 0 com.xiaomi.micloud.sdk
adb shell pm disable-user --user 0 com.xiaomi.midrop
adb shell pm disable-user --user 0 com.android.wallpaperbackup
adb shell pm disable-user --user 0 com.miui.antispam
adb shell pm disable-user --user 0 com.miui.touchassistant
adb shell pm disable-user --user 0 com.miui.userguide
adb shell pm disable-user --user 0 com.android.browser
adb shell pm disable-user --user 0 com.android.bookmarkprovider
adb shell pm disable-user --user 0 com.android.providers.partnerbookmarks
adb shell pm disable-user --user 0 com.android.bips
adb shell pm disable-user --user 0 com.android.printspooler
adb shell pm disable-user --user 0 com.google.android.printservice.recommendation
adb shell pm disable-user --user 0 com.android.contacts
adb shell pm disable-user --user 0 com.android.deskclock
adb shell pm disable-user --user 0 com.miui.calculator
adb shell pm uninstall --user 0 com.android.providers.downloads.ui
adb shell pm uninstall --user 0 com.miui.miservice
adb shell pm disable-user --user 0 com.android.thememanager
adb shell pm uninstall --user 0 com.mipay.wallet.in
adb shell pm uninstall --user 0 com.xiaomi.calendar
adb shell pm disable-user --user 0 com.android.mms
adb shell pm disable-user --user 0 com.android.contacts
adb shell pm disable-user --user 0 com.mi.android.globalFileexplorer
adb shell pm disable-user --user 0 com.xiaomi.miplay_client
adb shell pm uninstall --user 0 com.xiaomi.account
adb shell pm uninstall --user 0 com.xiaomi.mi_connect_service
adb shell pm uninstall --user 0 com.xiaomi.miplay_client
adb shell pm uninstall --user 0 com.xiaomi.micloud.sdk
adb shell pm disable-user --user 0 com.miui.gallery
adb shell pm uninstall --user 0 com.xiaomi.miplay_client
adb shell pm uninstall --user 0 com.netflix.partner.activation
adb shell pm disable-user --user 0 com.miui.player
